### ISSUE TITLE
'BDD' object has no attribute '_succ'?

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#61]
Hi Ioannis et al,

I'm really interested in recursive functions on BDDs. I have to design one in Cudd and was looking to prototype it with the much more flexible tulip-dd. I was looking at https://github.com/tulip-control/dd/blob/master/doc.md#design-principles and found this little gem. (I commented out the p = abs(u) because I didn't understand its need and it threw an error...)

`
def print_descendants(bdd, u, visited):
    #p = abs(u)
    i, v, w = bdd._succ[u]
    # visited ?
    if u in visited:
        return
    # remember
    visited.add(u)
    print(u)
    # u is terminal ?
    if v is None:
        return
    print_descendants(bdd, v, visited)
    print_descendants(bdd, w, visited)
`
Testing the function with say (also from the design principles)

`from dd import autoref as _bdd
bdd = _bdd.BDD()
bdd.declare('x', 'y', 'z')
u = bdd.add_expr('x /\ y')  # conjunction
visited = set()
print_descendants(bdd,u,visited)
`

I get thrown

`AttributeError: 'BDD' object has no attribute '_succ'`

Can you let me know if this has been deprecated or how to do something like this? Thanks!

**Comment by johnyf** [comment]
`_succ` is an attribute of the class `dd.bdd.BDD` (`dd.autoref.BDD` is used above (https://github.com/tulip-control/dd/issues/61#issue-687493604)), and the function `print_descendants` of the documentation is designed to be used with the class `dd.bdd.BDD`. The line `p = abs(u)` is necessary to obtain positive integers (non-negated references to nodes), because only positive integers are stored in the dictionary `dd.bdd.BDD._succ`.

The functions `enumerate_nodes` and `rectify_nodes` from https://github.com/tulip-control/dd/issues/59#issuecomment-680850300 could be used to collect the descendants of a node when using `dd.autoref.BDD`, as commented in https://github.com/tulip-control/dd/issues/59#issuecomment-682169409.

There are two layers, `dd.autoref.BDD` and `dd.bdd.BDD`. The class `dd.autoref.BDD` wraps external references to BDD nodes of `dd.bdd.BDD` as instances of the class `dd.autoref.Function`, and BDD nodes in `dd.bdd.BDD` are represented as integers (positive integers for non-negated node references, and negative integers for negated node references) . A motivation for this approach is to automate reference counting by using `dd.autoref.Function`:

https://github.com/tulip-control/dd/blob/890d191529bf302cdc3bf2afbad0395cf92054c0/dd/autoref.py#L308

https://github.com/tulip-control/dd/blob/890d191529bf302cdc3bf2afbad0395cf92054c0/dd/autoref.py#L327-L329

In contrast, reference counting with `dd.bdd.BDD` needs to be performed by the user.

The classes `dd.autoref.BDD` and `dd.cudd.BDD` are mostly similar and designed to be interchangeable. They have several methods similar to the class `dd.bdd.BDD`, but they are not interchangeable with the latter, one reason being reference counting.

**Comment by glarange** [comment]
OK, understood. Thanks, G
